### ISSUE TITLE
启动后调试失败

### ISSUE THREAD

**Issue by lxb0425** [BUAADreamer/Chinese-LLaVA-Med#2]
启动后使用以下参数返回422 不支持openai的方式吗
{
"model": "llava-v1.5",
"messages": [
{
"role": "user",
"content": [
{
"type": "text",
"text": "请告诉我这张图像里有什么，中文回复我"
},
{
"type": "image_url",
"image_url": {
"url": "https://th.bing.com/th/id/R.6b5df1bfe0e4778a44dba0753cd169c8?rik=QRQIMqvjWRCO5Q&riu=http%3a%2f%2fpic39.nipic.com%2f20140321%2f8857347_232251363165_2.jpg&ehk=7oAaMo6LCHJc%2bqpQ0IPvcH7v69jGRQhb2vDz%2fOd5720%3d&risl=&pid=ImgRaw&r=0"
}
}
]
}
],
"temperature": 0.7,
"top_p": 1,
"logprobs": false,
"top_logprobs": 0,
"n": 1,
"max_tokens": null,
"stop": null,
"stream": false,
"presence_penalty": 0,
"frequency_penalty": 0,
"user": "string",
"repetition_penalty": 1,
"session_id": -1,
"ignore_eos": false,
"skip_special_tokens": true,
"top_k": 40
}

**Comment by BUAADreamer** [comment]
您好，请先使用llama-factory配套代码完成本项目模型运行

**Comment by BUAADreamer** [comment]
以及发一下您运行的命令，谢谢

**Comment by lxb0425** [comment]
使用llama-factory的 CUDA_VISIBLE_DEVICES=0,1 API_PORT=7864 llamafactory-cli webchat /workspace/LLaMA-Factory/examples/inference/vllm.yaml 的界面方式是可以正常传图片的

使用llamafactory-cli api config/llava1_5_full_sft_infer.yaml的api方式传递上面的参数就返回422了

**Comment by BUAADreamer** [comment]
我和hiyouga讨论了一下，目前api确实还不支持图像调用，后续我们会支持
