### ISSUE TITLE
数据集与llama_factory兼容问题

### ISSUE THREAD

**Issue by AhLok-Chow** [BUAADreamer/Chinese-LLaVA-Med#6]
新的llama_factory库中，多模态的json文件中content内容需要加入/image的标识，这和目前的数据集格式不兼容。请问有考虑更新数据集，或者提供json文件和图像吗

**Comment by BUAADreamer** [comment]
可能后面会更新，但暂时没时间
您可以自行在每个messages的第一个assistant的content的首或尾加上`<image>`
